### ISSUE TITLE
Syntax error with seemingly well-formed RDF

### ISSUE THREAD

**Issue by ewrayjohnson** [niklasl/ldtr#8]
Loading RDF XML from the following when type is not specified: [http://purl.org/ontology/bibo/degrees](http://purl.org/ontology/bibo/degrees)
I get: 
```
SyntaxError: Expected ">", "\\U", "\\u", or [^\0- ,<,>,",{,},|,\^,`,\\] but " " found.
    at peg$buildStructuredError ([...]\node_modules\ldtr\lib\trig\parser.js:771:12)
    at peg$buildError ([...]\node_modules\ldtr\lib\trig\parser.js:783:12)
    at Proxy.peg$parse ([...]\node_modules\ldtr\lib\trig\parser.js:1279:11)
    at trigToJsonLd ([...]\node_modules\ldtr\lib\transcribers.js:23:23)
    at runNextTicks (node:internal/process/task_queues:60:5)
    at processImmediate (node:internal/timers:447:9)
    at process.topLevelDomainCallback (node:domain:161:15)
    at process.callbackTrampoline (node:internal/async_hooks:128:24)
    at async Proxy.read ([...]\node_modules\ldtr\lib\main.js:51:10)
```

**Comment by niklasl** [comment]
The resource is served as `application/xml`. Fixed in 65d5016e34bb3dce553543044d9e4f9a4fa4d528 by assuming RDF/XML (though it could technically be e.g. GRDDL or even XML+RDFa).
